
// Country codes and names in Hebrew
export const countries: { code: string; name: string }[] = [
  { code: 'il', name: 'ישראל' },
  { code: 'ad', name: 'אנדורה' },
  { code: 'ae', name: 'איחוד האמירויות הערביות' },
  { code: 'af', name: 'אפגניסטן' },
  { code: 'ag', name: 'אנטיגואה וברבודה' },
  { code: 'ai', name: 'אנגווילה' },
  { code: 'al', name: 'אלבניה' },
  { code: 'am', name: 'ארמניה' },
  { code: 'ao', name: 'אנגולה' },
  { code: 'ar', name: 'ארגנטינה' },
  { code: 'at', name: 'אוסטריה' },
  { code: 'au', name: 'אוסטרליה' },
  { code: 'az', name: 'אזרבייג\'ן' },
  { code: 'ba', name: 'בוסניה והרצגובינה' },
  { code: 'bb', name: 'ברבדוס' },
  { code: 'bd', name: 'בנגלדש' },
  { code: 'be', name: 'בלגיה' },
  { code: 'bg', name: 'בולגריה' },
  { code: 'bh', name: 'בחריין' },
  { code: 'br', name: 'ברזיל' },
  { code: 'by', name: 'בלארוס' },
  { code: 'ca', name: 'קנדה' },
  { code: 'ch', name: 'שווייץ' },
  { code: 'cl', name: 'צ\'ילה' },
  { code: 'cn', name: 'הרפובליקה העממית של סין' },
  { code: 'cy', name: 'קפריסין' },
  { code: 'cz', name: 'צ\'כיה' },
  { code: 'de', name: 'גרמניה' },
  { code: 'dk', name: 'דנמרק' },
  { code: 'ee', name: 'אסטוניה' },
  { code: 'eg', name: 'מצרים' },
  { code: 'es', name: 'ספרד' },
  { code: 'et', name: 'אתיופיה' },
  { code: 'fi', name: 'פינלנד' },
  { code: 'fr', name: 'צרפת' },
  { code: 'gb', name: 'הממלכה המאוחדת' },
  { code: 'ge', name: 'גאורגיה' },
  { code: 'gr', name: 'יוון' },
  { code: 'hu', name: 'הונגריה' },
  { code: 'id', name: 'אינדונזיה' },
  { code: 'ie', name: 'אירלנד' },
  { code: 'in', name: 'הודו' },
  { code: 'iq', name: 'עיראק' },
  { code: 'ir', name: 'איראן' },
  { code: 'it', name: 'איטליה' },
  { code: 'jo', name: 'ירדן' },
  { code: 'jp', name: 'יפן' },
  { code: 'ke', name: 'קניה' },
  { code: 'kr', name: 'קוריאה הדרומית' },
  { code: 'kz', name: 'קזחסטן' },
  { code: 'lb', name: 'לבנון' },
  { code: 'lt', name: 'ליטא' },
  { code: 'lv', name: 'לטביה' },
  { code: 'ly', name: 'לוב' },
  { code: 'ma', name: 'מרוקו' },
  { code: 'md', name: 'מולדובה' },
  { code: 'mx', name: 'מקסיקו' },
  { code: 'nl', name: 'ממלכת ארצות השפלה' },
  { code: 'no', name: 'נורווגיה' },
  { code: 'pl', name: 'פולין' },
  { code: 'pt', name: 'פורטוגל' },
  { code: 'ro', name: 'רומניה' },
  { code: 'ru', name: 'רוסיה' },
  { code: 'sa', name: 'ערב הסעודית' },
  { code: 'se', name: 'שוודיה' },
  { code: 'si', name: 'סלובניה' },
  { code: 'sy', name: 'סוריה' },
  { code: 'th', name: 'תאילנד' },
  { code: 'tn', name: 'תוניסיה' },
  { code: 'tr', name: 'טורקיה' },
  { code: 'ua', name: 'אוקראינה' },
  { code: 'us', name: 'ארצות הברית' },
  { code: 'uz', name: 'אוזבקיסטן' },
  { code: 'ye', name: 'תימן' },
  { code: 'za', name: 'דרום אפריקה' }
].sort((a, b) => a.name.localeCompare(b.name, 'he'));

export const getCountryByCode = (code: string): string => {
  const country = countries.find(c => c.code === code);
  return country ? country.name : '';
};

export const getCountryCodeByName = (name: string): string => {
  const country = countries.find(c => c.name === name);
  return country ? country.code : '';
};
